name: CI
on: [push, pull_request]

jobs:
  build-test-publish:
    # For tag pushes, we want to assure only the tag event triggers CI,
    # not the accompanying commit:
    if: "! startsWith(github.event.head_commit.message, 'Bump ') || startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Add miniconda to PATH
        run: echo "PATH=${HOME}/miniconda3/bin:${PATH}" >> $GITHUB_ENV

      - name: Setup conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh \
            --no-verbose -O miniconda.sh
          bash miniconda.sh -b
          conda config --set always_yes yes --set changeps1 no
          # Installing mamba, which is a much faster alternative for conda
          conda install -c conda-forge mamba
          # The last channel has the highest priority, making sure CPG Hail build is installed
          conda config --add channels bioconda --add channels conda-forge --add channels cpg
          # Installing tools needed to build and publish the package
          mamba install pip conda-build conda-verify anaconda-client

      - name: Build package
        run: mamba build conda/$(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

      - name: Install the local build
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: mamba install --use-local $(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

      - name: Run tests
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          cd test
          source test_combine_gvcfs.sh
          source test_sample_qc.sh

      - name: Upload to anaconda package repository
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
          upload ${HOME}/miniconda3/conda-bld/**/*.tar.bz2
