{% set data=load_setup_py_data() %}

package:
  name: cpg_qc
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  build:
    - python ==3.7.*
    - versionpy
    - click
    - pandas
    - pip:
      - hail

  run:
    - python ==3.7.*
    - versionpy
    - click
    - pandas
    - google-cloud-sdk
    - gsutil
    - pip:
      - hail
      - git+git://github.com/broadinstitute/gnomad_methods.git@master#egg=gnomad
      - google-cloud-secret-manager
      - google-api-python-client

test:
  commands:
    - cpg_qc --version

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}