{% set data=load_setup_py_data() %}

package:
  name: cpg_qc
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - versionpy
    - click
    - pandas
    - pip:
      - hail
      - git+https://github.com/broadinstitute/gnomad_methods@master
      - google-cloud-secret-manager
      - google-api-python-client

  run:
    - python >=3.6
    - versionpy
    - click
    - pandas
    - pip:
      - hail
      - git+https://github.com/vladsaveliev/gnomad_methods@master
      - google-cloud-secret-manager
      - google-api-python-client

test:
  commands:
    - cpg_qc --version

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}