{% set data=load_setup_py_data() %}

package:
  name: cpg_qc
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 3
  noarch: python

requirements:
  host:
    - python ==3.7.*
    - hail >=0.2.61
  run:
    - python ==3.7.*
    - hail >=0.2.61
    - click
    - pandas
    - google-cloud-sdk
    - google-cloud-storage
    - gnomad

test:
  commands:
    - sample_qc --version
    - combine_gvcfs --version

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}