{% set version = "0.4.0" %}

package:
  name: gnomad
  version: {{ version }}

source:
  git_url: https://github.com/broadinstitute/gnomad_methods.git

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6,<3.8
  run:
    - python
    - hail >=0.2.61
    - hdbscan
    - ipywidgets
    - scikit-learn
    - slackclient ==2.5.0

test:
  imports:
    - gnomad

about:
  home: https://github.com/broadinstitute/gnomad_methods
  summary: Hail utilities for the Genome Aggregation Database
