{% set name = 'hail' %}
{% set version = '0.2.61' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/populationgenomics/hail.git
  sha256: unused

build:
  number: 4

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - rsync
  host:
    - python >=3.6,<3.8
    - pyspark >=2.4,<2.4.2
    - openjdk 8.*
    - lz4
    - pytest-runner
    - pip
  run:
    - python
    - openjdk 8.*
    - pyspark 2.4.6
    - aiohttp
    - aiohttp-session
    - bokeh >1.1,<1.3
    - decorator <5
    - deprecated
    - gcsfs
    - humanize
    - hurry.filesize
    - nest-asyncio
    - parsimonious
    - pyjwt
    - python-json-logger ==0.1.11
    - requests
    - scipy
    - tabulate ==0.8.3
    - tqdm ==4.42.1
    - dill
    - asyncinit

test:
  imports:
    - hail

about:
  home: https://hail.is
  dev_url: https://github.com/hail-is/hail
  license: MIT
  license_file: LICENSE
  summary: |
    Hail is Python-based data analysis tool for working with genomic data.

extra:
  skip-lints:
    - uses_vcs_url
  recipe-maintainers:
    - raivivek
